### ISSUE TITLE
Use case examples

### ISSUE THREAD

**Issue by hertzg** [aimnadze/port-forward#1]
👋 Hello, I was curious what would be the best use case example for this app?
As far as I understand this does TCP/TLS proxying with added benefit of TLS termination (tls <> tcp proxying). Have you had a chance to look at [Traefik](https://docs.traefik.io/https/tls/) for example?

**Comment by aimnadze** [comment]
Port Forward exists for only one reason and that is port forwarding. This makes it different from other tools.

So far my use cases were debugging HTTPS requests and bypassing security limitations (such as when a database running on a server is listening to only a local port).

**Comment by aimnadze** [comment]
Traefik seems to incorporate other features like reverse proxying which I consider outside of the scope of port forwarding. Of course if you're already familiar to it you may not want to have another port forwarder. But if you just found an application that sends something to some other server and you want to check what it its Port Forward might be a good point to start.

**Comment by hertzg** [comment]
I see the value in having a very lightweight tcp proxy, would it be a good idea to have the use case example in README.md?

**Comment by aimnadze** [comment]
Port forwarding has plenty of use cases. I documented only the most valuable relationships with the software. See the README.md

**Comment by aimnadze** [comment]
Closing with the hope that the original question was fully answered.
